### ISSUE TITLE
Is there any way/shortcode to show content only if user has ALL expired licenses

### ISSUE THREAD

**Issue by rohitp-bsf** [awesomemotive/edd-additional-shortcodes#21]
From the readme file, I can see that there is a shortcode to `Show content only if the user has expired licenses`, I just want a new shortcode to display content only if the user has all expired licenses.

**Comment by ashleyfae** [comment]
I'm afraid we don't have a shortcode for that. The ones we do have apply if _at least_ one license is expired; it doesn't require that they all be.
