### ISSUE TITLE
items_not_in_cart?

### ISSUE THREAD

**Issue by Chaddeus** [awesomemotive/edd-additional-shortcodes#9]
Hello @cklosowski , this is a possible enhancement to this extension. Perhaps an edd_items_not_in_cart shortcode?

Where we could show/hide content based on certain items NOT being in the cart. :)

Thanks!

**Comment by Chaddeus** [comment]
Or this could be [edd_items_in_cart not="1,2,24,27"]...[/edd_items_in_cart]

**Comment by cklosowski** [comment]
Yep, can get that added. I'll probably make it follow the same pattern as the `edd_items_in_cart` shortcode, for consistency.

**Comment by cklosowski** [comment]
I'm going to punt this to 1.4.2, so I can get a bug fix release out for the recent SL 3.8 release.
